INSERT INTO books(isbn,title,genre,author,description) VALUES
       ('1603864377','Principia Mathematica - Volume One','Mathematics','Alfred North Whitehead,Bertrand Russell','First volume of Principia Mathematica'),
       ('1603864385','Principia Mathematica - Volume Two','Mathematics','Alfred North Whitehead,Bertrand Russell','Second volume of Principia Mathematica'),
       ('1603864393','Principia Mathematica - Volume Three','Mathematics','Alfred North Whitehead,Bertrand Russell','Third volume of Principia Mathematica'),
       ('000647988X','A Game of Thrones','Fantasy drama','George R. R. Martin','A Game of Thrones is the first novel in A Song of Ice and Fire, a series of fantasy novels by the American author George R. R. Martin'),
       ('0553579908','A Clash of Kings','Fantasy drama','George R. R. Martin','A Clash of Kings is the second novel in A Song of Ice and Fire, an epic fantasy series by American author George R. R. Martin expected to consist of seven volumes'),
       ('055357342X','A Storm of Swords','Fantasy drama','George R. R. Martin','A Storm of Swords is the third of seven planned novels in A Song of Ice and Fire, a fantasy series by American author George R. R. Martin'),
       ('9780006486121','A Feast for Crows','Fantasy drama','George R. R. Martin','A Feast for Crows is the fourth of seven planned novels in the epic fantasy series A Song of Ice and Fire by American author George R. R. Martin'),
       ('9780006486114','A Dance with Dragons','Fantasy drama','George R. R. Martin','A Dance with Dragons is the fifth novel of seven planned in the epic fantasy series A Song of Ice and Fire by American author George R. R. Martin'),
       ('0735211124','The Swoly Bible: The BroScience Way of Life','Parody','Dom Mazzetti','A self-proclaimed expert on everything, Dom Mazzetti is an Italian-American bro in his early twenties that hails from the tri-state area. Confidently stupid with good intentions, Dom refuses to grow up, and takes glee in his day-to-day responsibility-free existence. At his core - way down deep to his perfectly sculpted core - Dom is a great guy, just misunderstood. Dom is the type of guy that will give you the shirt off his back, even if you dont want his shirt, just so he can be shirtless. This is his first book.');
